### ISSUE TITLE
在office365的word上失败了

### ISSUE THREAD

**Issue by Garlandal** [idf/LaTeX2Word-Equation#1]
版本是Office365 16.0.6366,感觉是没有进入粘贴板，开发者大大有空看下啦~

**Comment by idf** [comment]
Can you formally describe the issue? Which webpage are you copying the LaTeX from? Which OS are you using? 

Cheers.

**Comment by Garlandal** [comment]
Oops, that's my fault, i made a mistake, please forgive my disturb~
